name: Run docs workflow
on:
  push:
    branches:
      - main
    paths:
      - docs/**
jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        run: |
          curl -XPOST -u "kujtimiihoxha:${{secrets.USER_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/go-services/gs-docs/actions/workflows/main.yaml/dispatches --data '{"ref": "main"}'